In [1]:
from teacher.fuzzy import FuzzyVariable, FuzzyContinuousSet, FuzzyDiscreteSet
from teacher.datasets import load_german, load_compas, load_adult
import numpy as np

In [2]:
from flocalx.rule import Rule, FuzzyRule, NumericAntecedent, CategoricalAntecedent, FuzzyAntecedent, RuleSet, FuzzyRuleSet

In [3]:
fs1 = FuzzyContinuousSet("low",[0, 0.5, 1])
fs2 = FuzzyContinuousSet("medium",[0.5, 1, 1.5])
fs3 = FuzzyContinuousSet("high",[1, 1.5, 2])

In [4]:
fv = FuzzyVariable("fv", [fs1, fs2, fs3])

In [5]:
a = NumericAntecedent(0, [0, 1])

In [6]:
b = CategoricalAntecedent(1, [['red', True]])

In [7]:
r = Rule([a, b], 1)

In [8]:
print(r)

[0 is [0, 1], 1 is [['red', True]]] -> 1


In [9]:
x = [0.5, 'red']

In [10]:
r.match(x)

1

In [11]:
c = FuzzyAntecedent(0, fs1)

In [12]:
r2 = FuzzyRule([c, b], 1, 0.5)
x2 = [0.25, 'red']

r2.match(x2)

0.25

In [13]:
import json

with open('./data/rulesets/german_dt_test.json', 'r') as f:
    ruleset = json.load(f)


In [14]:
with open('./data/rulesets/crisp/compas_dt.json', 'r') as f:
    ruleset = json.load(f)

dataset = load_compas()
antecedent_order = {v: k for k, v in dataset['idx_features'].items()}
dataset_info = {
    'antecedent_order': antecedent_order,
    'discrete': set(dataset['discrete']),
    'continuous': set(dataset['continuous'])
}

rs = RuleSet.from_json(ruleset, dataset_info)

In [15]:
x = dataset['X'][0]

In [16]:
x

array([69,  1,  1,  5,  0,  1,  0,  0,  0,  0,  0])

In [17]:
[r for r in rs.rules if r.match(x) > 0]

[[4 is [-inf, 4.5], 0 is [37.5, inf], 10 is [-inf, 3.5], 3 is [['African-American', False]], 6 is [['charge', False]]] -> Medium-Low]

In [18]:
len(rs.rules)

1457

In [19]:
len(set(rs.rules))

1457

In [20]:
[r for r in set(rs.rules) if r.match(x) > 0]

[[4 is [-inf, 4.5], 0 is [37.5, inf], 10 is [-inf, 3.5], 3 is [['African-American', False]], 6 is [['charge', False]]] -> Medium-Low]

In [21]:
y_decoded = dataset['label_encoder'][dataset['class_name']].inverse_transform(dataset['y'][0:100])

In [22]:
rs.score(dataset['X'][0:100], y_decoded)

0.73

In [23]:
with open('./data/rulesets/fuzzy/adult_fdt.json', 'r') as f:
    ruleset = json.load(f)

dataset = load_adult()
antecedent_order = {v: k for k, v in dataset['idx_features'].items()}
dataset_info = {
    'antecedent_order': antecedent_order,
    'discrete': set(dataset['discrete']),
    'continuous': set(dataset['continuous'])
}

In [24]:
fuzzy_rule = ruleset[5]

In [25]:
fr = FuzzyRule.from_json(fuzzy_rule, dataset_info)

In [26]:
dataset['X'][0]

array([  39,    6,    9,    4,    0,    1,    4,    1, 2174,    0,   40,
         38])

In [27]:
x = dataset['df'].iloc[0].to_numpy()

In [28]:
df = dataset['df']
X_df = df.drop(columns=[dataset['class_name']])

In [29]:
x = X_df.iloc[0].to_numpy()
x

array([39, 'State-gov', 'Bachelors', 'Never-married', 'Adm-clerical',
       'Not-in-family', 'White', 'Male', 2174, 0, 40, 'United-States'],
      dtype=object)

In [30]:
fr.match(x)

0.0

In [31]:
fr

1.0 : [5 is [['Husband', True]], 2 is [['Bachelors', True]], 8 is 0, 4 is [['Craft-repair', True]], 11 is [['United-States', True]], 1 is [['Private', True]], 9 is 0, 6 is [['White', True]], 10 is 1] -> <=50K

In [32]:
frs = FuzzyRuleSet.from_json(ruleset, dataset_info)

In [33]:
len(frs.rules)

2591

In [35]:
x

array([39, 'State-gov', 'Bachelors', 'Never-married', 'Adm-clerical',
       'Not-in-family', 'White', 'Male', 2174, 0, 40, 'United-States'],
      dtype=object)

In [37]:
frs.predict(X_df.iloc[0:100].to_numpy())

['<=50K',
 '>50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K']

In [38]:
y_decoded = dataset['label_encoder'][dataset['class_name']].inverse_transform(dataset['y'][0:100])

In [39]:
frs.score(X_df.iloc[0:100].to_numpy(), y_decoded)

0.61